helper files for cget.sh and some recipes
eclipse-4diac/4diac-toolchain pull request #1
Opened 2023-05-31 10:30 UTC by jwalt

this adds some helper files that will be used in subsequent commits

2023-05-31 10:32 UTC, azoitl requested changes

2023-05-31 10:32 UTC, azoitl commented on etc/cget/cmake/autotools-build.cmake
> +##############################################################################
please add an eclipse copyright header. You can have a look on CMake files from 4diac FORTE for examples.

2023-05-31 11:04 UTC, jwalt commented
I have added the corresponding recipes as well to show how the aux files are needed

2023-05-31 13:15 UTC, azoitl requested changes
I'm not sure what to do about the copyright header for the h files. Even if they are generated something should be there.

2023-05-31 13:15 UTC, azoitl commented on etc/cget/recipes/cross-toolchain/rsync
> +#!/bin/sh
please add a copyright header here as well

2023-06-01 09:39 UTC, jwalt commented
fixed the license problem and moving recipes to a different pull request

2023-06-12 21:48 UTC, azoitl approved these changes

2023-06-12 21:48 UTC, merged